name: Run Tests and Coverage

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run tests and coverage
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7  # Replace 'x' with the desired Python version (e.g., 3.8, 3.9)

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r api/requirements.txt
        pip install pytest-json-report

    - name: Run tests and generate JSON report
      run: |
        pytest --json-report --json-report-file=pytest_report.json api/tests

    - name: Show test results
      run: |
        jq -r '.summary | "Total: \(.total), Passed: \(.passed), Failed: \(.failed), Skipped: \(.skipped)"' pytest_report.json
    
    - name: Run tests with coverage
      run: |
        coverage run -m pytest api/tests

    - name: Generate coverage report
      run: coverage xml
    
    - name: Upload coverage data to codecov (optional)
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}