name: Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: pip install -r api/requirements.txt
      - name: Run tests
        run: pytest api/tests
      - name: Get code coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

    if: always()

  merge:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Check if tests passed
        run: |
          if [ "${{ steps.test.outputs.result }}" != "passed" ]; then
            echo "Tests failed, aborting merge."
            exit 1
          fi
      - name: Merge branch
        run: |
          git merge ${{ github.event.pull_request.head.ref }}

  report:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Print code coverage
        run: |
          echo "Code coverage: ${{ steps.test.outputs.coverage }}"
          echo "Tests approved: ${{ steps.test.outputs.approved }}"
          echo "Tests failed: ${{ steps.test.outputs.failed }}"
          echo "Tests skipped: ${{ steps.test.outputs.skipped }}"
