name: Run Tests and Coverage

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run tests and coverage
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Replace 'x' with the desired Python version (e.g., 3.8, 3.9)

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r api/requirements.txt
        pip install pytest-json-report

    - name: Run tests and generate JSON report
      run: |
        pytest --json-report --json-report-file=pytest_report.json api/tests

    - name: Show test results
      run: |
        grep -oP '(?<=total": )[0-9]+' pytest_report.json > total_tests.txt
        grep -oP '(?<=passed": )[0-9]+' pytest_report.json > passed_tests.txt
        grep -oP '(?<=failed": )[0-9]+' pytest_report.json > failed_tests.txt
        grep -oP '(?<=skipped": )[0-9]+' pytest_report.json > skipped_tests.txt
        awk '{print "Total: " $1 ", Passed: " $2 ", Failed: " $3 ", Skipped: " $4}' total_tests.txt passed_tests.txt failed_tests.txt skipped_tests.txt > test_results.txt
        cat test_results.txt

    - name: Run tests with coverage
      run: |
        coverage run -m pytest api/tests

    - name: Generate coverage report
      run: coverage xml