name: Run Tests and Coverage

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run tests and coverage
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Replace 'x' with the desired Python version (e.g., 3.8, 3.9)

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r api/requirements.txt

    - name: Run tests with coverage
      run: pytest --cov=api 

    - name: Get code coverage
      uses: codecov/codecov-action@v3
      with:
          token: ${{ secrets.CODECOV_TOKEN }}

    if: always()

  report:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Print code coverage
        run: |
          echo "Code coverage: ${{ steps.test.outputs.coverage }}"
          echo "Tests approved: ${{ steps.test.outputs.approved }}"
          echo "Tests failed: ${{ steps.test.outputs.failed }}"
          echo "Tests skipped: ${{ steps.test.outputs.skipped }}"